CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <>''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <>''),
    done BOOLEAN,
    projectId integer REFERENCES projects(id)
);

INSERT INTO projects(name, prioriry, description, deliverydate)
    values('Make a web app',1,'Using JavaScript', '2021-12-28');

--INSERT TASKS
INSERT INTO tasks(name, done, projectId)
    values('donwload node',false,1);
